#!/usr/bin/env bash
# =============================================================================
# Generated by adapters/claude-code/adapter.sh — do not edit.
# Wrapper for hook: validate-frontmatter
# Reads Claude Code native PreToolUse/PostToolUse/Notification JSON from stdin,
# transforms it into the neutral schema, and pipes the result to validate-frontmatter.sh.
# =============================================================================
set -eo pipefail

INPUT=$(cat)
HOOK_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Translate CC native fields to the neutral schema
NEUTRAL=$(echo "$INPUT" | jq -c '{
  event: "after-tool-use",
  tool: (.tool_name // ""),
  args: (.tool_input // {title: .title, message: .message}),
  session_id: (.session_id // ""),
  cwd: (.cwd // ""),
  framework: "claude-code",
  platform_dir: ".claude",
  dispatcher_name: "CLAUDE.md"
}')

echo "$NEUTRAL" | bash "$HOOK_DIR/validate-frontmatter.sh"
